apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-2
  name: dep-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: dep-2
  ports:
    - protocol: TCP
      port: 8028
      targetPort: 80
  type: ClusterIP
  clusterIP: None
