apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    mycka: simplilearn
spec:
 containers:
   - name: mycontainer
     image: nginx:latest
     ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  selector:
    mycka: simplilearn
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
        #  type: ClusterIP
        #  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    mycka: simplilearn
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
  type: NodePort
