apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "8Gi"
        cpu: "800m"
      requests:
        memory: "7Gi"
        cpu: "400m"
  priorityClassName: low-priority
