apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
     limits:
      memory: "8Gi"
     requests:
      memory: "7Gi"
  nodeSelector:
    harddisk: ssd
  priorityClassName: high-priority 
