apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/storage
  capacity:
    storage: 1G

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  volumeName: pv-demo
  storageClassName: local-storage
  accessModes:
   - ReadWriteMany
  volumeMode: Filesystem
  resources:
   requests:
    storage: 500M

---


apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/tmp"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-demo
