version: "3"

services:
  
  redis_service:
    image: redis:7.0.9
    ports:
      - "6379"
    networks: 
      - frontend
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
  
  httpd_service:
    image: httpd:2.4.56
    ports:
      - "8080:80"
    networks:
      - frontend
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
    
  postgres_service:
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    environment: 
      - POSTGRES_PASSWORD=redhat
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
  
networks:
  frontend: 
  backend: 

volumes:
  db-data: 
