apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: nginx-app-pod
      labels:
        env: dev
    spec:
#      nodeSelector:
#       kubernetes.io/os: linux
      containers:
      - name: java-app
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: dev
  type: NodePort
