apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: internal-deployment
  name: internal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-deployment
  template:
    metadata:
      labels:
        app: internal-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external-deployment
  name: external-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: external-deployment
  template:
    metadata:
      labels:
        app: external-deployment
    spec:
      containers:
      - image: nginx
        name: nginx

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: internal-deployment
  name: internal-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8008
  selector:
    app: internal-deployment

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-deployment
  name: external-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: external-deployment
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-deployment
  name: lb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: external-deployment
  type: LoadBalancer
