apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: internal-deployment
  name: internal-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8008
  selector:
    app: internal-deployment
status:
  loadBalancer: {}
